# Wazuh Docker Copyright (C) 2019 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    build: wazuh
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    volumes:
     - wazuh-docker_ossec_backup:/migration/ossec_backup:ro
     - wazuh-docker_filebeat:/migration/filebeat_backup:ro
     - wazuh-docker_filebeat-lib:/migration/filebeat-lib_backup:ro
     - wazuh-docker_postfix:/migration/postfix_backup:ro

  wazuh-worker:
    build: wazuh
    hostname: wazuh-worker
    restart: always
    ports:
      - "1514/udp"
      - "514/udp"
      - "1515"
      - "1516"
      - "55000"
    volumes:
     - wazuh-docker_ossec_backup2:/migration/ossec_backup:ro
     - wazuh-docker_filebeat2:/migration/filebeat_backup:ro
     - wazuh-docker_filebeat-lib2:/migration/filebeat-lib_backup:ro
     - wazuh-docker_postfix2:/migration/postfix_backup:ro

  elasticsearch:
    build: elasticsearch
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g

  kibana:
    build: kibana
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh

  nginx:
    build: nginx
    hostname: nginx
    restart: always
    environment:
      - NGINX_PORT=443
      - NGINX_CREDENTIALS
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kibana
    links:
      - kibana:kibana

volumes:
  wazuh-docker_ossec_backup:
    external: true
  wazuh-docker_filebeat:
    external: true
  wazuh-docker_filebeat-lib:
    external: true
  wazuh-docker_postfix:
    external: true
  wazuh-docker_ossec_backup2:
    external: true
  wazuh-docker_filebeat2:
    external: true
  wazuh-docker_filebeat-lib2:
    external: true
  wazuh-docker_postfix2:
    external: true