# Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    build: wazuh
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    volumes:
     - ./master_configuration.sh:/entrypoint-scripts/master_configuration.sh
     - ossec_backup:/backup/ossec_backup
     - filebeat:/backup/filebeat_backup
     - filebeat-lib:/backup/filebeat-lib_backup
     - postfix:/backup/postfix_backup

  wazuh-worker:
    build: wazuh
    hostname: wazuh-worker
    restart: always
    ports:
      - "1514/udp"
      - "514/udp"
      - "1515"
      - "1516"
      - "55000"
    volumes:
      - ./worker_configuration.sh:/entrypoint-scripts/worker_configuration.sh
      - ossec_backup2:/backup/ossec_backup
      - filebeat2:/backup/filebeat
      - filebeat-lib2:/backup/filebeat-lib
      - postfix2:/backup/postfix

  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.9.5_7.2.1
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g

  kibana:
    image: wazuh/wazuh-kibana:3.9.5_7.2.1
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
  nginx:
    image: wazuh/wazuh-nginx:3.9.5_7.2.1
    hostname: nginx
    restart: always
    environment:
      - NGINX_PORT=443
      - NGINX_CREDENTIALS
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kibana
    links:
      - kibana:kibana

volumes:
  ossec_backup:
  filebeat:
  filebeat-lib:
  postfix:
  ossec_backup2:
  filebeat2:
  filebeat-lib2:
  postfix2: